clc;
clear;
close all;

addpath(genpath('./cifti_utilities'));
addpath(genpath('./read_write_cifti_32ksurface'));
addpath(genpath('./plotSpread'));

Cluster_correct_ttestpaired_cifti(...
    'Similarity_toABCDavg_MEDIC_allruns.dscalar.nii',...
    'Similarity_toABCDavg_TOPUP_allruns.dscalar.nii',...
    [0.01, 0.001, 0.0001],...
    0.05,...
    'Similarity_toABCDavg_MEDICvTOPUP');
